<?php

namespace App\Http\Requests\Payment;

use App\Http\Requests\ApiFormRequest;

class InitializePaymentRequest extends ApiFormRequest
{
    public function authorize(): bool
    {
        return true;
    }

    public function rules(): array
    {
        return [
            'amount' => ['prohibited'],
            'currency' => ['prohibited'],
            'reference' => ['prohibited'],
            'provider' => ['prohibited'],
            'status' => ['prohibited'],
            'payment_status' => ['prohibited'],
        ];
    }

    public function messages(): array
    {
        return [
            'amount.prohibited' =>
                'Payment amount is calculated by the server.',

            'currency.prohibited' =>
                'Payment currency is configured by the server.',

            'reference.prohibited' =>
                'Payment reference is generated by the server.',

            'provider.prohibited' =>
                'Payment provider is selected by the server.',

            'status.prohibited' =>
                'Payment status cannot be assigned by the client.',

            'payment_status.prohibited' =>
                'Payment status cannot be assigned by the client.',
        ];
    }
}